package test:ser

interface serializer {
    resource serializer-resource {
        constructor()
        serialize-i32: static func(self: serializer-resource, v: s32) -> string
    }

    serialize-i32: func(v: s32) -> string
}

world test-serialize {
    import serializer
}

world test-serializer {
    export serializer
}

world test {
    export run: func() -> result<string, string>
}
