package test:ser

interface serializer {
    serialize-i32: func(v: s32) -> string
}

world test-serialize {
    import serializer
}

world test-serializer {
    export serializer
}

world test {
    export run: func() -> result<string, string>
}
