package serde:serde

interface serialize {
    use raw-serializer.{serializer}

    resource serialize {
        serialize: func(serializer: serializer)
    }
}

interface raw-serialize {
    resource serialize {}
}

interface raw-serializer {
    resource serializer {}
}

interface serializer {
    use raw-serialize.{serialize}

    resource serializer {
        serialize-some: static func(self: serializer, value: borrow<serialize>)
    }
}

world serde-demo {
    import serializer
    import raw-serializer
    export serialize
    export raw-serialize
}
