default world serde-serializer-client {
    import serializer: interface {
        use pkg.serde-ser.{s128, usize, u128}

        test: func(x: s128) -> u128
    }

    export serialize: interface {
        use pkg.serde-ser.{s128, usize, u128}

        test: func(x: s128) -> u128
    }
}
