package serde:serde;

interface serde-types {
    record s128 {
        le-hi: u64,
        le-lo: u64,
    }

    record u128 {
        le-hi: u64,
        le-lo: u64,
    }

    record usize {
        val: u32,
    }
}
