default world serde-deserializer-provider {
    import deserialize: interface {
        use pkg.serde-de.{s128, unexpected, usize, u128}

        test: func(x: s128) -> u128
    }

    export deserializer: interface {
        use pkg.serde-de.{s128, unexpected, usize, u128}

        test: func(x: s128) -> u128
    }
}
